# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce838b2d0a4f2bd4a302550529a0ef3ed00878072cd66b5fbd6849f7a9cf90578a68f000a15ab438b09e8e34cdd5a3be69740f66f8c97e6563aa84c70ea6b0aa

test:
  secret_key_base: 2b4dfa69a4ad04130bdaba60d01cd9b8e85d78b666685170cf62aec56ef9d6c167d0146f189295d8a9732ba7ce803ceefe8db0229114ef87fd1feb0a27ad202e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
